### ISSUE TITLE
ENOENT: no such file or directory when host contains protocol

### ISSUE THREAD

**Issue by WtfJoke** [mbogh/test-ssl-action#5]
>ENOENT: no such file or directory, open '/home/runner/work/project/project/output/undefined'

If you pass a domain with protocol e.g https://example.com (instead of example.com) the report file cannot be found.

Example:
```yaml
- uses: mbogh/test-ssl-action@v2
  with:
    host: https://example.com
    grade: A
```

The cause is, that the report is generated without the protocol eg. example.com...json

The issue is most likely on this line (a potential fix, either validate host or change startsWith to contains):
https://github.com/mbogh/test-ssl-action/blob/1aa048cc077393880f141bf0a86f1395ee2d6f50/index.js#L30
